AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - spec/**/*
    - bin/**/*
    - test/**/*
    - Gemfile
    - Rakefile
    - config.ru
    - vendor/**/*

Style/AndOr:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Style/HashSyntax:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/LineLength:
  Exclude:
    - spec/**/*.rb
